checks:
    go: true

build:
    environment:
        go: go1.9.2
    nodes:
        analysis:
            tests:
                override:
                    - go-scrutinizer-run
                    - govet-run
                    - golint-run
                    